/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as RiskAnalyticsRouteImport } from './routes/risk-analytics'
import { Route as PermitIntelligenceRouteImport } from './routes/permit-intelligence'
import { Route as OrchestrationRouteImport } from './routes/orchestration'
import { Route as LiveReplayRouteImport } from './routes/live-replay'
import { Route as IncidentInvestigationRouteImport } from './routes/incident-investigation'
import { Route as GeospatialRouteImport } from './routes/geospatial'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as AgentWorkflowRouteImport } from './routes/agent-workflow'
import { Route as IndexRouteImport } from './routes/index'

const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskAnalyticsRoute = RiskAnalyticsRouteImport.update({
  id: '/risk-analytics',
  path: '/risk-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const PermitIntelligenceRoute = PermitIntelligenceRouteImport.update({
  id: '/permit-intelligence',
  path: '/permit-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestrationRoute = OrchestrationRouteImport.update({
  id: '/orchestration',
  path: '/orchestration',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveReplayRoute = LiveReplayRouteImport.update({
  id: '/live-replay',
  path: '/live-replay',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentInvestigationRoute = IncidentInvestigationRouteImport.update({
  id: '/incident-investigation',
  path: '/incident-investigation',
  getParentRoute: () => rootRouteImport,
} as any)
const GeospatialRoute = GeospatialRouteImport.update({
  id: '/geospatial',
  path: '/geospatial',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentWorkflowRoute = AgentWorkflowRouteImport.update({
  id: '/agent-workflow',
  path: '/agent-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-workflow': typeof AgentWorkflowRoute
  '/command-center': typeof CommandCenterRoute
  '/compliance': typeof ComplianceRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/evidence': typeof EvidenceRoute
  '/geospatial': typeof GeospatialRoute
  '/incident-investigation': typeof IncidentInvestigationRoute
  '/live-replay': typeof LiveReplayRoute
  '/orchestration': typeof OrchestrationRoute
  '/permit-intelligence': typeof PermitIntelligenceRoute
  '/risk-analytics': typeof RiskAnalyticsRoute
  '/simulation': typeof SimulationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-workflow': typeof AgentWorkflowRoute
  '/command-center': typeof CommandCenterRoute
  '/compliance': typeof ComplianceRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/evidence': typeof EvidenceRoute
  '/geospatial': typeof GeospatialRoute
  '/incident-investigation': typeof IncidentInvestigationRoute
  '/live-replay': typeof LiveReplayRoute
  '/orchestration': typeof OrchestrationRoute
  '/permit-intelligence': typeof PermitIntelligenceRoute
  '/risk-analytics': typeof RiskAnalyticsRoute
  '/simulation': typeof SimulationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-workflow': typeof AgentWorkflowRoute
  '/command-center': typeof CommandCenterRoute
  '/compliance': typeof ComplianceRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/evidence': typeof EvidenceRoute
  '/geospatial': typeof GeospatialRoute
  '/incident-investigation': typeof IncidentInvestigationRoute
  '/live-replay': typeof LiveReplayRoute
  '/orchestration': typeof OrchestrationRoute
  '/permit-intelligence': typeof PermitIntelligenceRoute
  '/risk-analytics': typeof RiskAnalyticsRoute
  '/simulation': typeof SimulationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-workflow'
    | '/command-center'
    | '/compliance'
    | '/digital-twin'
    | '/evidence'
    | '/geospatial'
    | '/incident-investigation'
    | '/live-replay'
    | '/orchestration'
    | '/permit-intelligence'
    | '/risk-analytics'
    | '/simulation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-workflow'
    | '/command-center'
    | '/compliance'
    | '/digital-twin'
    | '/evidence'
    | '/geospatial'
    | '/incident-investigation'
    | '/live-replay'
    | '/orchestration'
    | '/permit-intelligence'
    | '/risk-analytics'
    | '/simulation'
  id:
    | '__root__'
    | '/'
    | '/agent-workflow'
    | '/command-center'
    | '/compliance'
    | '/digital-twin'
    | '/evidence'
    | '/geospatial'
    | '/incident-investigation'
    | '/live-replay'
    | '/orchestration'
    | '/permit-intelligence'
    | '/risk-analytics'
    | '/simulation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentWorkflowRoute: typeof AgentWorkflowRoute
  CommandCenterRoute: typeof CommandCenterRoute
  ComplianceRoute: typeof ComplianceRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  EvidenceRoute: typeof EvidenceRoute
  GeospatialRoute: typeof GeospatialRoute
  IncidentInvestigationRoute: typeof IncidentInvestigationRoute
  LiveReplayRoute: typeof LiveReplayRoute
  OrchestrationRoute: typeof OrchestrationRoute
  PermitIntelligenceRoute: typeof PermitIntelligenceRoute
  RiskAnalyticsRoute: typeof RiskAnalyticsRoute
  SimulationRoute: typeof SimulationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-analytics': {
      id: '/risk-analytics'
      path: '/risk-analytics'
      fullPath: '/risk-analytics'
      preLoaderRoute: typeof RiskAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permit-intelligence': {
      id: '/permit-intelligence'
      path: '/permit-intelligence'
      fullPath: '/permit-intelligence'
      preLoaderRoute: typeof PermitIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestration': {
      id: '/orchestration'
      path: '/orchestration'
      fullPath: '/orchestration'
      preLoaderRoute: typeof OrchestrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-replay': {
      id: '/live-replay'
      path: '/live-replay'
      fullPath: '/live-replay'
      preLoaderRoute: typeof LiveReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incident-investigation': {
      id: '/incident-investigation'
      path: '/incident-investigation'
      fullPath: '/incident-investigation'
      preLoaderRoute: typeof IncidentInvestigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geospatial': {
      id: '/geospatial'
      path: '/geospatial'
      fullPath: '/geospatial'
      preLoaderRoute: typeof GeospatialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-workflow': {
      id: '/agent-workflow'
      path: '/agent-workflow'
      fullPath: '/agent-workflow'
      preLoaderRoute: typeof AgentWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentWorkflowRoute: AgentWorkflowRoute,
  CommandCenterRoute: CommandCenterRoute,
  ComplianceRoute: ComplianceRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  EvidenceRoute: EvidenceRoute,
  GeospatialRoute: GeospatialRoute,
  IncidentInvestigationRoute: IncidentInvestigationRoute,
  LiveReplayRoute: LiveReplayRoute,
  OrchestrationRoute: OrchestrationRoute,
  PermitIntelligenceRoute: PermitIntelligenceRoute,
  RiskAnalyticsRoute: RiskAnalyticsRoute,
  SimulationRoute: SimulationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
